 create table employee (
 	id bigint primary key identity(1,1),
  name varchar(32) not null,
 	position varchar(100) not null,
 	hiredate datetime not null,
 	base_wage decimal(10,2) not null,
 	working_age_subsidy decimal(10,2),
 	overtime decimal(10,2),
  meals_subsidy decimal(10,2),
  secrecy_subsidy decimal(10,2),
  communication_fee decimal(10,2),
  jyw_commission_ratio decimal(10,2),
  commencement_ratio int,
  completion_ratio int,
  renovate_commission_ratio decimal(10,2),
  bank_card_number varchar(30) not null,
  identity_card_number varchar(20) not null,
  transportation_allowance decimal(10,2),
  post_allowance decimal(10,2),
  leave_date datetime,
  storage_charge decimal(10,2),
  total_charge decimal(10,2),
  charge_per_month decimal(10,2),
  charge decimal(10,2),
  company_id int not null
 )

