CREATE TABLE project_commision (
	id int primary key identity(1,1),
	designer nvarchar(50),
	ac_number varchar(6),
	contract_id varchar(20),
	customer_name varchar(20),
	contract_total decimal(18, 2),
	purchase_agent_fee decimal(18, 2),
	project_change_total decimal(18, 2),
	branch varchar(20),
	customer_pay decimal(18, 2),
	pay_contract_ratio decimal(18, 2),
	pay_project_ratio decimal(18, 2),
	contract_state int,
	contract_date datetime,
	actual_start_time datetime,
	actual_end_time datetime,
	balance_time datetime,
	desginer_assistant varchar(20),
	first_commision decimal(18, 2),
	first_commision_date datetime,
	balance_commision decimal(18, 2),
	balance_commision_date datetime,
	design_commision_rate decimal(2, 2),
	desginer_assistant_commision_rate decimal(2, 2)
)